spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_matchpet
    username: root
    password: Lmtlf1620*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Configuración de correo electrónico
  mail:
    host: smtp.gmail.com
    port: 587
    username: luis.tlf.2006@gmail.com
    password: Lmtlf1620*
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

  # Configuración de seguridad OAuth2 (sin valores de cliente secretos)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${PROD_GOOGLE_CLIENT_ID}
            client-secret: ${PROD_GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile

google:
  api:
    key: ${GOOGLE_API_KEY} # Se carga de una variable de entorno

gemini:
  model:
    name: gemini-1.5-flash-001

jwt:
  access:
    secret: ${PROD_JWT_ACCESS_SECRET}
    expiration: 43200000
  refresh:
    secret: ${PROD_JWT_REFRESH_SECRET}
    expiration: 2592000000

# Configuración de MercadoPago en desarrollo
mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN}

# Configuración del frontend
frontend:
  url: http://localhost:5173
