"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@)_empuvb-jamy)lm5egtu=iam--y@d@slt1kk^j_y#dh$fq_g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps de terceros
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    # Tus apps
    'administracion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_matchpet',       # Nombre exacto de tu DB MySQL
        'USER': 'root',              # Usuario de tu DB
        'PASSWORD': 'Lmtlf1620*',              # Contraseña de tu DB (pon la tuya)
        'HOST': '127.0.0.1',         # O 'db' si estás usando Docker
        'PORT': '3306',
    }
}


# Password validationclient:733 [vite] connecting...
client:827 [vite] connected.
installHook.js:1 API Error: AxiosError
overrideMethod @ installHook.js:1
:8000/api/adoptantes/:1  Failed to load resource: net::ERR_CONNECTION_REFUSED
:8000/api/adoptantes/?page=3:1  Failed to load resource: the server responded with a status of 404 (Not Found)
installHook.js:1 API Error: Object
overrideMethod @ installHook.js:1
installHook.js:1 Error fetching adoptantes: AxiosError
overrideMethod @ installHook.js:1
:8000/api/adoptantes/?page=3:1  Failed to load resource: the server responded with a status of 404 (Not Found)
installHook.js:1 API Error: Object
overrideMethod @ installHook.js:1
installHook.js:1 Error fetching adoptantes: AxiosError
overrideMethod @ installHook.js:1
:8000/api/adoptantes/?page=4:1  Failed to load resource: the server responded with a status of 404 (Not Found)
installHook.js:1 API Error: Object
overrideMethod @ installHook.js:1
installHook.js:1 Error fetching adoptantes: AxiosError
overrideMethod @ installHook.js:1

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuración REST Framework
# settings.py
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173", # Puerto por defecto de Vite
    "http://127.0.0.1:5173",
]

CORS_ALLOW_ALL_ORIGINS = True
