# Generated by Django 5.2.7 on 2025-12-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(db_column='animal_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento_aprox', models.DateField(db_column='fecha_nacimiento_aprox')),
                ('descripcion_personalidad', models.TextField(db_column='descripcion_personalidad')),
                ('compatible_ninos', models.BooleanField(db_column='compatible_niños', default=False)),
                ('compatible_otras_mascotas', models.BooleanField(db_column='compatible_otras_mascotas', default=False)),
                ('esta_vacunado', models.BooleanField(db_column='esta_vacunado', default=False)),
                ('esta_esterilizado', models.BooleanField(db_column='esta_esterilizado', default=False)),
                ('historial_medico', models.TextField(db_column='historial_medico')),
                ('fecha_ingreso_refugio', models.DateField(db_column='fecha_ingreso_refugio')),
                ('fecha_actualizacion', models.DateTimeField(db_column='fecha_actualizacion')),
                ('raza_id', models.IntegerField(db_column='raza_id')),
                ('genero_id', models.IntegerField(db_column='genero_id')),
                ('tamano_id', models.IntegerField(db_column='tamano_id')),
                ('nivel_energia_id', models.IntegerField(db_column='nivel_energia_id')),
                ('estado_adopcion_id', models.IntegerField(db_column='estado_adopcion_id')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'Animales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.AutoField(db_column='refugio_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('persona_contacto', models.CharField(db_column='persona_contacto', max_length=255)),
                ('descripcion', models.TextField()),
                ('url_sitio_web', models.CharField(db_column='url_sitio_web', max_length=255)),
                ('fecha_registro', models.DateTimeField(db_column='fecha_registro')),
                ('fecha_actualizacion', models.DateTimeField(db_column='fecha_actualizacion')),
            ],
            options={
                'verbose_name': 'Refugio',
                'verbose_name_plural': 'Refugios',
                'db_table': 'Refugios',
                'managed': False,
            },
        ),
    ]
