# Generated by Django 5.2.7 on 2025-10-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('hash_contraseña', models.TextField()),
                ('fecha_creacion_perfil', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_temperamento', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adoptante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=100, unique=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento_aprox', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('tamaño', models.CharField(blank=True, choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10)),
                ('descripcion_personalidad', models.TextField(blank=True)),
                ('nivel_energia', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10)),
                ('compatible_niños', models.BooleanField(default=False)),
                ('compatible_otras_mascotas', models.BooleanField(default=False)),
                ('foto_principal_url', models.TextField(blank=True)),
                ('estado_adopcion', models.CharField(choices=[('Disponible', 'Disponible'), ('En proceso', 'En proceso'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=20)),
                ('fecha_ingreso_refugio', models.DateField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.especie')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.raza')),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.refugio')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=3)),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Fallido', 'Fallido'), ('Reembolsado', 'Reembolsado')], default='Pendiente', max_length=20)),
                ('gateway_transaccion_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('mensaje_donante', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.animal')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.donante')),
                ('refugio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.refugio')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('Enviada', 'Enviada'), ('En revisión', 'En revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Enviada', max_length=20)),
                ('notas_del_refugio', models.TextField(blank=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.adoptante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTemperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.animal')),
                ('temperamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.temperamento')),
            ],
            options={
                'unique_together': {('animal', 'temperamento')},
            },
        ),
    ]
