# Generated by Django 5.2.7 on 2025-12-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.AutoField(db_column='adoptante_id', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(db_column='fecha_registro')),
            ],
            options={
                'verbose_name': 'Adoptante',
                'verbose_name_plural': 'Adoptantes',
                'db_table': 'adoptantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(db_column='donacion_id', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_donacion', models.DateTimeField(db_column='fecha_donacion')),
                ('mensaje', models.TextField(db_column='mensaje_donante')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.AutoField(db_column='solicitud_id', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(db_column='fecha_solicitud')),
                ('estado_solicitud', models.CharField(db_column='estado', max_length=50)),
            ],
            options={
                'verbose_name': 'Solicitud de Adopción',
                'verbose_name_plural': 'Solicitudes de Adopción',
                'db_table': 'solicitud_adopcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSpring',
            fields=[
                ('id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario App',
                'verbose_name_plural': 'Usuarios App',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animales',
        ),
        migrations.AlterModelTable(
            name='refugio',
            table='refugios',
        ),
    ]
