# Generated by Django 5.2.7 on 2025-12-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_adoptante_donacion_solicitudadopcion_usuariospring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdoptante',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion.usuariospring')),
                ('fecha_nacimiento', models.DateField(db_column='fecha_nacimiento')),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Perfil Adoptante',
                'verbose_name_plural': 'Perfiles Adoptantes',
                'db_table': 'perfil_adoptante',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Adoptante',
        ),
        migrations.AlterModelTable(
            name='solicitudadopcion',
            table='solicitudes_adopcion',
        ),
        migrations.AlterModelTable(
            name='usuariospring',
            table='usuarios',
        ),
    ]
