# Generated by Django 5.2.7 on 2025-12-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_perfiladoptante_delete_adoptante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFoto',
            fields=[
                ('id', models.AutoField(db_column='foto_id', primary_key=True, serialize=False)),
                ('url_foto', models.TextField(db_column='url_foto')),
                ('es_principal', models.BooleanField(db_column='es_principal', default=False)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'animal_fotos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(db_column='especie_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Catálogo: Especies',
                'db_table': 'especies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoAdopcion',
            fields=[
                ('id', models.AutoField(db_column='estado_adopcion_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Adopción',
                'verbose_name_plural': 'Catálogo: Estados Adopción',
                'db_table': 'estados_adopcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.AutoField(db_column='estado_solicitud_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Solicitud',
                'verbose_name_plural': 'Catálogo: Estados Solicitud',
                'db_table': 'estados_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(db_column='genero_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Catálogo: Géneros',
                'db_table': 'generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelEnergia',
            fields=[
                ('id', models.AutoField(db_column='nivel_energia_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Nivel Energía',
                'verbose_name_plural': 'Catálogo: Niveles de Energía',
                'db_table': 'niveles_energia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(db_column='raza_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Catálogo: Razas',
                'db_table': 'razas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(db_column='tamano_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Catálogo: Tamaños',
                'db_table': 'tamanos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'managed': False, 'verbose_name': 'Animal', 'verbose_name_plural': 'Gestión de Animales'},
        ),
        migrations.AlterModelOptions(
            name='perfiladoptante',
            options={'managed': False, 'verbose_name': 'Perfil de Adoptante', 'verbose_name_plural': 'Perfiles de Adoptantes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudadopcion',
            options={'managed': False, 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Gestión de Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='usuariospring',
            options={'managed': False, 'verbose_name': 'Usuario App', 'verbose_name_plural': 'Usuarios Registrados'},
        ),
    ]
